### PR TITLE
API: implement SRR and various maintenance/improvement tasks.

### LINKED ISSUE #114: Allow user to specify queries in validation sampling
It'd be nice if the user could specify the target indices a user asks about. i.e.,

``` yaml
targets: ["a", "b", "c", "d", "e"]
samplers:
  ValidationSampling: {queries: [(0, 1, 2), (1, 2, 3), (2, 3, 4)]}
```

would show these targets to the user:

*  `["a", "b", "c"]` (via target indices 0, 1, 2)
* `["b", "c", "d"]` (via target indices 1, 2, 3)
* `["c", "d", "e"]` (via target indices 2, 3, 4)

cc @kushinm

### PR DESCRIPTION
**Pull request by stsievert**
**What does this PR implement?**
It allows the following:

* Implements an "synchronous round robin" scheme that searches `n_search` queries (instead of asynchronously).
* Specifying the triplets indices in validation sampling.
    * ...by specifying `queries: [[0, 1, 2], [3, 4, 5]]` in `init.yaml` under the `samplers` heading.
* Customizing the participant ID
    * ...by visiting `http://localhost:8421/?puid=foobar`.
* Allow customizing `samplers_per_user`
    * Related: API: allow `/query?ident=`.
    * ...by specifying `samplers_per_user` in `init.yaml`.
* Allow user to initialize embedding with pre-computed embedding
    * (which is especially relevant given the downloadable online embedding)
* Doc changes:
    * Clarify ``sampling`` key in init.yml.
    * Change "ARR" to mean "async RR" instead of "adaptive RR"
    * Add initial embedding to offline embedding
* Maint:
    * better error handling on dashboards/getting embeddings.
    * Better HTML serving of targets (prefetch instead of custom solution)
    * Adds `torch.no_grad` in `score`.

**Backwards incompatible changes**
* Renames `RandomSampling` to `Random` to fit with naming scheme of other samplers.
    * (but warns if wrong file uploaded)
* (internal) renames `Runner` to `Sampler`.

**Reference issues/PRs**
This closes #114 and #117.

### CODE REVIEW

**Comment by stsievert** [comment]
@crcox does this resolve your issue? I think this is similar to the external ID/`ext_id` you mentioned in #117.

**Comment by crcox** [comment]
Yes, that will do the trick.
Clarification on validation queries: is it something like
```
samplers: {
    Validation: {},
    queries: [[0, 1, 2], [3, 4, 5]]
}
```
or
```
samplers: {
    Validation: {
        queries: [[0, 1, 2], [3, 4, 5]]
    }
}
```
?

**Comment by stsievert** [comment]
[basic.yaml][1] shows an example of how to specify the indices:

``` yaml
samplers:
  ARR: {}
  RandomSampling: {}
  Validation:
    queries: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
```

[1]:https://github.com/stsievert/salmon/pull/118/files#diff-2fc66a608a86c29df3a91e8aca44c35ad97060e30581479c17c3f3e76450bd53

**Comment by crcox** [comment]
Perfect, thanks!

**Comment by stsievert** [comment]
Most tests are passing locally, all except 3. That's a non-issue; I'm testing that errors get logged, and can't restart docker in the middle of the tests. If I could, those tests would pass.

**Pull request merged**
